### ISSUE TITLE
Great work & publishing to Maven

### ISSUE THREAD

**Issue by MrPowers** [yaooqinn/itachi#1]
Great work on this project.  Looks really useful.  I will help you get users ;)

Are you publishing this to Maven yet?

Once we get this lib in Maven, I can submit a README PR with an installation / quick start section that grabs the reader's attention and motivates them to start using the lib.

It might be cool to give this lib a single-word name - something like [kyuubi](https://github.com/yaooqinn/kyuubi) would be pretty sweet ;)

Thanks for all your open source Spark contributions.  You do a lot to help the community!

**Comment by yaooqinn** [comment]
Thanks, @MrPowers

It's not in the maven repo yet, if you are interested in this. I can add you as a maintainer of this repo. 
And we can start by naming it.

**Comment by MrPowers** [comment]
@yaooqinn - sounds like a good plan to me :)

**Comment by yaooqinn** [comment]
I have sent the invitation

**Comment by MrPowers** [comment]
@yaooqinn - what should be call the repo?  Naruto, Ibara, looks like [we have lots of good options](https://naruto.fandom.com/wiki/Naruto_Uzumaki!!_(chapter_1)).  Anything short and that's easy to pronounce works for me!

**Comment by yaooqinn** [comment]
yea, I also like a short and clear name. Too many good options might be a bad thing :) to reach a final decision.

Let's create a list of candidates
 - konoha - https://naruto.fandom.com/wiki/Konohagakure
 - itachi https://naruto.fandom.com/wiki/Itachi_Uchiha
 - sharingan https://naruto.fandom.com/wiki/Sharingan
 - pending for your suggestions

**Comment by MrPowers** [comment]
Let's go with itachi - [this guy looks awesome](https://www.youtube.com/watch?v=ojR3bLgc2cY&ab_channel=AMVtion).  I am going to have to watch this series ;)

**Comment by yaooqinn** [comment]
done 👍🏼

**Comment by MrPowers** [comment]
@yaooqinn - I haven't used Maven a lot, but am excited to try something different than SBT.

Should I just install Maven on my machine?  Can you tell me the command to run the test suite?  Thank you!

**Comment by yaooqinn** [comment]
Yeah, for now, you need to install maven locally first and run the command in the ci
https://github.com/yaooqinn/itachi/blob/master/.github/workflows/ci.yml

BTW, I'm OK, we switch to SBT or something else, or support both build tools like spark

**Comment by yaooqinn** [comment]
Shall we move this work under a more public space for people to reach? like awesome-spark?

**Comment by yaooqinn** [comment]
cc @zero323 WDYT？

**Comment by MrPowers** [comment]
@yaooqinn - I publish my open source projects to Maven directly with the sbt-sonatype plugin, [more details here](https://github.com/MrPowers/spark-daria#publishing).  You'll need to do some work on your end if you'd like to publish, namely the [Sonatype](https://github.com/olafurpg/sbt-ci-release#sonatype) and [GPG](https://github.com/olafurpg/sbt-ci-release#gpg) setup steps.

I can submit a pull request with the info that needs to be added to this repo if you'd like to publish via sbt-sonatype.

Here's [an example of where you'll be able to find the JAR files in Maven](https://repo1.maven.org/maven2/com/github/mrpowers/spark-fast-tests_2.12/) once they're published.

**Comment by yaooqinn** [comment]
yes, thanks for your very detailed suggestion. I will check that soon @MrPowers

**Comment by oluies** [comment]
> > Shall we move this work under a more public space for people to reach? like awesome-spark?
> 
> WDYT @eliasah @oluies

Looks intresting, can it be made avaliable at Spark Packages?

**Comment by MrPowers** [comment]
@oluies - thanks for commenting!

Spark Packages has unfortunately [been broken for a few years](https://github.com/databricks/sbt-spark-package/issues/31) and looks like [it's abandonware](https://github.com/databricks/sbt-spark-package/issues/48).

I had to shift all my stuff off Spark packages, but [it's still causing my users confusion](https://github.com/MrPowers/spark-fast-tests/discussions/85).  I'll bring this up to the Databricks product team and see if they can either archive the sbt-spark-package repo or start maintaining it again.  Clear messaging either way would be helpful for the community.

**Comment by MrPowers** [comment]
@yaooqinn - Just a friendly reminder to get your Maven namespace setup 😉  It'll be good for you to have one of these in any case.

[Here are the instructions](https://github.com/olafurpg/sbt-ci-release#sonatype).

I'd recommend just getting `com.yaooqinn` to keep it simple.

I'll help you with all the hard work of getting the plugins setup, so the actual publishing part will just be a one command process.

**Comment by zero323** [comment]
> I'd recommend just getting `com.yaooqinn` to keep it simple.

 That might be the way to go. However, if you want to use `org.awesomespark` (thinking about it as something like community hub)  I am fine with that ‒ just ping directly on matrix.org or keybase.

**Comment by yaooqinn** [comment]
> @yaooqinn - Just a friendly reminder to get your Maven namespace setup 😉 It'll be good for you to have one of these in any case.

Sorry for the delay. It’s the Chinese New Year Festival now.😬

> 
> I'd recommend just getting com.yaooqinn to keep it simple.

I filed a New Project ticket in SonaType JIRA w/ `com.github.yaooqinn` % `itachi` a few days ago （also add `mrpowers` as）and I’ll make some time to get the rest done in the next 2 or 3 days

FYI, https://issues.sonatype.org/browse/OSSRH-64476

**Comment by MrPowers** [comment]
@yaooqinn - Happy New Year!!!!

**Comment by yaooqinn** [comment]
Hi @MrPowers, I've followed your instructions and succeeded in pushing a SNAPSHOT but failed for a RELEASE see: https://github.com/yaooqinn/itachi/actions?query=workflow%3ARelease

And Happy New Year to ALL.

**Comment by yaooqinn** [comment]
Oh, it seems to succeed at last with a 'long' retry :)

**Comment by MrPowers** [comment]
@yaooqinn - great job getting the JAR published.  That's huge, we can start getting users now.

I [updated the README](https://github.com/yaooqinn/itachi/pull/5) to explain how to add itachi to a project.  Let me know what you think.

Let's map out some additional work for this project.  Would be cool to get some other open source contributors too - this is a great learning project!

**Comment by yaooqinn** [comment]
> Let's map out some additional work for this project. Would be cool to get some other open source contributors too


I wonder if there is a way to get all those rejected PRs for adding extra SQL
functions to Spark main from Github. 
Then we can contact the authors of these PRs and 
see if they're willing to help and contribute to the project. 
Or we could just make an announcement on Spark's mailing list.

**Comment by MrPowers** [comment]
@yaooqinn - just FYI, I'm [starting to post to Reddit](https://www.reddit.com/r/apachespark/comments/lq6wml/my_experience_contributing_to_the_spark_codebase/) and will write other content to let people know about itachi.

Reaching out on the PRs and letting ppl know that some functions are probably better fits for itachi is another great idea.

Will keep marketing and trying to get users ;)

**Comment by MrPowers** [comment]
Also, closing this issue cause the JAR file is in Maven now!

**Comment by yaooqinn** [comment]
thanks a lot for your help!
