### ISSUE TITLE
Rename default branch to main

### ISSUE THREAD

**Issue by MrPowers** [yaooqinn/itachi#7]
Calling the default branch "main" is the current thing to do.

I've switched over all my other projects and it wasn't too bad, see [this guide](https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/).

I'm trying to get all the projects I work on switched so I don't need to remember what the main branch is called for every project.

**Comment by yaooqinn** [comment]
Done, thanks, @MrPowers
